# Generated by Django 5.0.6 on 2024-06-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_list',
            old_name='first_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='book_list',
            old_name='last_name',
            new_name='name',
        ),
    ]
