# Generated by Django 5.0.6 on 2024-06-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_first_name_book_list_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
    ]
